clarify inmanta module name vs Python package name
inmanta/inmanta-module-template pull request #17
Opened 2022-01-05 09:06 UTC by FloLey

With modules v2 there is a difference between the inmanta module name (my_module) and the Python package name (inmanta-module-my-module). The difference exists in the inmanta-module- prefix and the underscores/dashes.

This PR updates the module template to use the inmanta module name instead of the python package name for the module directory name to minimize confusion. This way the developer will never really interact with the Python package name directly.

issue inmanta/inmanta-core#3555

2022-01-06 13:11 UTC, sanderr approved these changes

2022-01-07 07:51 UTC, arnaudsjs requested changes

2022-01-07 07:51 UTC, arnaudsjs commented on Jenkinsfile
> +                        ls
Why do we need this line?

2022-01-07 08:34 UTC, FloLey commented on Jenkinsfile
> +                        ls
I forgot to remove that :p

2022-01-07 08:58 UTC, arnaudsjs approved these changes

2022-01-07 09:00 UTC, merged